Библиотека "traceback" используется в Python для отображения трассировки стека, то есть печати
информации об исключении и последующих вызовах функций, которые привели к возникновению исключения.
Она помогает в отладке и идентификации причин возникновения ошибок в программе.

|                                                                      |                                                                                                             |
|----------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `traceback.print_tb(tb, limit=None, file=None)`                      | Выводит трассировку стека в заданный файл (по умолчанию в sys.stdout) в виде списка строк                   |
| `traceback.print_exception(etype, value, tb, limit=None, file=None)` | Выводит полную информацию об исключении, включая тип и значение исключения, трассировку стека и подробности |
| `traceback.print_exc(limit=None, file=None, chain=True)`             | Выводит трассировку стека последнего возникшего исключения                                                  |
| `traceback.format_tb(tb, limit=None)`                                | Возвращает трассировку стека в виде списка строк                                                            |
| `traceback.format_exception(etype, value, tb, limit=None)`           | Возвращает полную информацию об исключении в виде списка строк                                              |
| `traceback.format_exc(limit=None, chain=True)`                       | Возвращает трассировку стека последнего возникшего исключения в виде строки                                 |

### print_tb
Используется для вывода трассировки стека в стандартном выводе
```python
import traceback

try:
    # некоторый код, в котором может произойти исключение
    x = 1 / 0
except:
    traceback.print_tb(sys.exc_info()[2])
```

### print_exception
Используется для вывода полной информации об исключении, включая тип, значение и трассировку стека
```python
import traceback

try:
    # некоторый код, в котором может произойти исключение
    x = 1 / 0
except:
    traceback.print_exception(*sys.exc_info())
```

### format_exc
Используется для получения трассировки стека последнего возникшего исключения в виде строки
```python
import traceback

try:
    # некоторый код, в котором может произойти исключение
    x = 1 / 0
except:
    error_traceback = traceback.format_exc()
    print(error_traceback)
```
